notifier:
    messages:
      - 'A MESSAGE'
    enabled: true
    chat_id: 715390857
    token: '7093567136:AAHvflgRH0cof6oW4FAzYlthpb8T3hbBak8'

providers:
    mercadolibre:
        base_url: 'https://inmuebles.mercadolibre.com.ar'
        sources:
          - '/departamentos/alquiler/capital-federal/belgrano-o-belgrano-r-o-belgrano-chico-o-belgrano-c-o-belgrano-barrancas/departamento-3-ambientes'
        filtros_meli: '_Cocheras_1_TOTAL*AREA_60-*'

    zonaprop:
        base_url: 'https://www.zonaprop.com.ar'
        sources:
          - '/departamentos-alquiler-coghlan-belgrano-belgrano-c-belgrano-belgrano-chico-belgrano-belgrano-r-belgrano-mas-de-1-garage-mas-60-m2-cubiertos.html'
        filtros_meli: 
disable_ssl:  false
