notifier:
    messages:
      - 'A MESSAGE'
    enabled: true
    chat_id: 715390857
    token: '7093567136:AAHvflgRH0cof6oW4FAzYlthpb8T3hbBak8'

providers:
    provider_a:
        base_url: <URL>
        sources:
          - <PATH>
disable_ssl: true | false
