providers:
    provider_a: mercadolibre
        base_url: https://inmuebles.mercadolibre.com.ar
        sources:
          - /departamentos/alquiler/capital-federal/belgrano-o-belgrano-r-o-belgrano-chico-o-belgrano-c-o-belgrano-barrancas/departamento-3-ambientes
disable_ssl:  false
